export const ADD_PASSENGER = "ADD_PASSENGER";
export const UPDATE_PASSENGER = "UPDATE_PASSENGER";
export const DELETE_PASSENGER = "DELETE_PASSENGER";
export const CHANGE_SEAT = "CHANGE_SEAT";

export const BOOK_SEAT = "BOOK_SEAT";
export const CANCEL_SEAT = "CANCEL_SEAT";
export const UPDATE_SEAT = "UPDATE_SEAT";
export const CHECKIN_SEAT = "CHECKIN_SEAT";

export const ADD_ANCILLARY_SERVICE = "ADD_ANCILLARY_SERVICE";
export const DELETE_ANCILLARY_SERVICE = "DELETE_ANCILLARY_SERVICE";
export const UPDATE_ALL_ANCILLARY_SERVICES = "UPDATE_ALL_ANCILLARY_SERVICES";

export const ADD_SPECIAL_MEAL = "ADD_SPECIAL_MEAL";
export const DELETE_SPECIAL_MEAL = "DELETE_SPECIAL_MEAL";
export const UPDATE_ALL_SPECIAL_MEALS = "UPDATE_ALL_SPECIAL_MEALS";

export const ADD_SHOPPING_ITEM = "ADD_SHOPPING_ITEM";
export const DELETE_SHOPPING_ITEM = "DELETE_SHOPPING_ITEM";
export const UPDATE_ALL_SHOPPING_ITEMS = "UPDATE_ALL_SHOPPING_ITEMS";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const SIGNUP = "SIGNUP";

export const ADD_ANCILLARY_SERVICE_PASSENGER =
  "ADD_ANCILLARY_SERVICE_PASSENGER";
export const DELETE_ANCILLARY_SERVICE_PASSENGER =
  "DELETE_ANCILLARY_SERVICE_PASSENGER";

export const ADD_SPECIAL_MEAL_PASSENGER = "ADD_SPECIAL_MEAL_PASSENGER";
export const DELETE_SPECIAL_MEAL_PASSENGER = "DELETE_SPECIAL_MEAL_PASSENGER";

export const ADD_SHOPPING_ITEM_PASSENGER = "ADD_SHOPPING_ITEM_PASSENGER";
export const DELETE_SHOPPING_ITEM_PASSENGER = "DELETE_SHOPPING_ITEM_PASSENGER";
